### ISSUE TITLE
Please release new version with methodToJs → method_ToJs

### ISSUE THREAD

**Issue by marcinkoziej** [zploskey/bs-puppeteer#129]
Hi, I see you have fixed the use of `methodToJs` in Request.re that prohibits to build the package with current bs-platform (7.2.2). However, in redex/package index the newest version is 0.12 - which does not contain this fix. Could You please make a release?

Thanks for doing this work! :star:

**Comment by zploskey** [comment]
Thanks for the reminder on this. Version 0.13 is now published with these changes.
